### ISSUE TITLE
[Suggestion] Add option to lower volume of clicking altar noise

### ISSUE THREAD

**Issue by Goldenlion5648** [TeamDman/Zen-Summoning#14]
The noise is currently kind of loud, is it possible to make it softer, or add an option in zenscript?

**Comment by jamesjimmy88** [comment]
I second this, the anvil sound is way too loud. An option to change what sound plays would be nice, too.

**Comment by TeamDman** [comment]
Fixed in 1.1.1
Should be live soon.
https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/2909372
