### ISSUE TITLE
Summons no longer working on latest version

### ISSUE THREAD

**Issue by Saereth** [TeamDman/Zen-Summoning#19]
I updated interactions to the lastest build of zen summoning and now the zombie villager will no longer summon. User reported issue here:

https://github.com/FTBTeam/FTB-Interactions/issues/872

I tried this myself in a fresh dev environment and confirmed its not working. I can manually spawn in one with a command or spawn egg, no error in the logfile that I see.

**Comment by TeamDman** [comment]
Resolved via https://github.com/FTBTeam/FTB-Interactions/issues/872#issuecomment-634086476
