### ISSUE TITLE
Spawn entities in center, rather than in corner

### ISSUE THREAD

**Issue by solunareclipse1** [TeamDman/Zen-Summoning#21]
currently, summoned entities will always spawn in the northwest corner of the block they spawn on. while this works, it would probably look a little bit nicer if they spawned in the center of the block instead. block center is at x+0.5 z+0.5.
additionally, allowing the script syntax to support decimals for coordinates would also be a nice addition.

**Comment by TeamDman** [comment]
Should be added in newest ver
https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/3625241
