### ISSUE TITLE
Summoning altar has same unlocalized name as Aether Legacy Enchanter (tile.altar.name)

### ISSUE THREAD

**Issue by solunareclipse1** [TeamDman/Zen-Summoning#22]
both the summoning altar and the enchanter from aether legacy use the same unlocalized name, tile.altar.name. this means they both show up with the same name in game. 
![2021-02-16_17 21 07](https://user-images.githubusercontent.com/26941050/108134208-66a04580-707b-11eb-82f6-a632eb97ae5f.png)
![2021-02-16_17 21 11](https://user-images.githubusercontent.com/26941050/108134213-6bfd9000-707b-11eb-8bf2-a9d95beabbb7.png)

**Comment by TeamDman** [comment]
Uploaded build
https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/3408149
Seemed to have launched and entered game without issues, but haven't done extensive testing.

**Comment by solunareclipse1** [comment]
no problem, ill let you know if i encounter any issues
