### ISSUE TITLE
Illusioner does not work with zen summoning

### ISSUE THREAD

**Issue by Goldenlion5648** [TeamDman/Zen-Summoning#25]
When using this script:
```
import crafttweaker.api.item.IItemStack;
import crafttweaker.api.item.IIngredient;
import mods.zensummoning.SummoningDirector;
import mods.zensummoning.SummoningAttempt;
import mods.zensummoning.SummoningInfo;
import mods.zensummoning.MobInfo;


SummoningDirector.addSummonInfo(
    SummoningInfo.create()
        .setCatalyst(<item:minecraft:bone>)
        .setReagents([<item:minecraft:leather>*2,<item:minecraft:beef>])
        .addMob(MobInfo.create()
            .setMob(<entitytype:minecraft:illusioner>)
            .setOffset(1,2,1)
            .setSpread(1,1,1)
        )
);
```
it does not get loaded in, but replacing "illusioner" with "zombie" does work

**Comment by TeamDman** [comment]
haven't tested myself yet, but you aren't on peaceful right?

**Comment by Goldenlion5648** [comment]
I meant the JEI recipe doesn't even show up

**Comment by Goldenlion5648** [comment]
What the heck? It works, just does not show in JEI when its the illusioner.

**Comment by TeamDman** [comment]
I think the way I upgraded the spawn egg code for the recipe might prevent stuff from working if the entity doesn't have an egg. In previous versions, you could hack the egg to be anything, but it's a little different now. Will try and make sure there's a fallback

**Comment by TeamDman** [comment]
New build will be available [here](https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/3423680) once approved
