### ISSUE TITLE
Altar's inventory is cleared every time you leave the world and rejoin 

### ISSUE THREAD

**Issue by RobertHDPotatoes** [TeamDman/Zen-Summoning#29]
Ever since the update to 1.3.3, the altar clears it's inventory every time you leave and rejoin the world. Also, as a side note, for some reason, the latest version I can download is 1.3.1 through my launcher (GDLauncher) so I have to manually download the latest version from the CurseForge's website directly. Not sure if this is a problem on CurseForge's end or something else weird going on, but GDLauncher says "The installed version of this mod has been removed from CurseForge, so you will only be able to get it as part of legacy modpacks."

**Comment by TeamDman** [comment]
Files were marked as 1.16.4 instead of 1.16.5, will make sure to update jar names and have proper version tagged for future release. The new versions should be tagged 1.16.5 now
Working on investigating inventory issues

**Comment by TeamDman** [comment]
Thanks, should be fixed in newest ver
https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/3625241
