### ISSUE TITLE
Passengers don't work

### ISSUE THREAD

**Issue by RobertHDPotatoes** [TeamDman/Zen-Summoning#30]
Alright, I may be wrong. Although, I can't get passengers to work the way they should, even though I'm using the same exact format as a command. So, I am trying to spawn a Phantom, with the passenger being a zombie. The vanilla command for this is: 

/summon phantom ~ ~1 ~ {Passengers:[{id:"minecraft:zombie"}]}

So, my .setData looks like this: 

	.setData({
	Passengers:
		[{id:"minecraft:zombie"}]
	})
)

(Pastebin of the full .zs file: https://pastebin.com/5KWHhsFe)

The phantom spawns, but it will not spawn with a passenger. Is this a limitation of Zen Summoning/CraftTweaker or am I just an idiot? I'm more inclined to believe it's the latter, but I'm having trouble finding documentation on CraftTweaker for my specific use case. If it's not a bug feel free to close, but I would really appreciate a link to some documentation to figure out what I'm doing wrong or tips on what to fix, thanks!

**Comment by TeamDman** [comment]
Looks like passengers require custom support beyond deserializing NBT. I've copied the logic used by vanilla, your script should work as-is on the latest build
https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/3633674
Thanks for the feedback!

**Comment by RobertHDPotatoes** [comment]
Awesome, just tested it out and it works perfectly now. Thanks for the fast response and fix!
