### ISSUE TITLE
Issues concerning latest version scripting

### ISSUE THREAD

**Issue by ChaosDogG** [TeamDman/Zen-Summoning#32]
So I'm attempting to make a recipe for a piglin that can survive in the overworld, but when I wrote the script, the game got mad at me saying that the imports were invalid. I'll include the files for the summon script and my log
[summoning.txt](https://github.com/TeamDman/Zen-Summoning/files/9276018/summoning.txt)
[crafttweaker.log](https://github.com/TeamDman/Zen-Summoning/files/9276020/crafttweaker.log)

**Comment by ChaosDogG** [comment]
i figured out the issues i was having! apparently it doesnt like the entity being chosen how it is in the readme and the imports for CT are out of date. mayhaps updating it so the proper imports are used alongside using <entitytype:modid:entityid> so the game knows where to get the entity you want to summon! other than that, it doesnt seem to have any further issues!

**Comment by TeamDman** [comment]
Thanks for the heads up, the script in the readme should be good now
