### ISSUE TITLE
[1.16.5] Script is not working on server

### ISSUE THREAD

**Issue by Subthy** [TeamDman/Zen-Summoning#33]
Hello,
I have ran in a problem that the scrip I made is not working on server, but is working in singleplayer. Script that is in the server and on the client are identical. Why would that be happening?

**Comment by TeamDman** [comment]
- What version of the mod is running on the server
- Pls provide the script to help debug
- Logs from the server would also potentially help

Could just be a mod issue, older versions had this problem and I might have missed something

**Comment by Subthy** [comment]
The version is 1.3.6 for 1.16.5
Script - https://pastebin.com/LT2tPVnH
Log - 
[logs_latest (1).log](https://github.com/TeamDman/Zen-Summoning/files/9379904/logs_latest.1.log)

If ya need anything else, just ask.

**Comment by TeamDman** [comment]
Are the recipes showing in JEI? that was one of the symptoms from the last time; the recipes wouldn't show
Also just realized this is for 1.16, unfortunately I can't even get old versions of the mod building since Forge no longer supports it so I don't think I can fix this

**Comment by Subthy** [comment]
Yeah the recipes are not showing. 
What do you mean Forge no longer supports it? You can still make mods and fix issues on 1.16.5.  A lot of people do that still

**Comment by TeamDman** [comment]
![image](https://user-images.githubusercontent.com/9356891/185671695-4bf0ea25-8332-43d0-8c3c-c440e0047ddd.png)

Gradle already giving issues that idk how to fix

![image](https://user-images.githubusercontent.com/9356891/185671793-c47b69b1-772a-4ecf-894c-653350eb513f.png)
