### ISSUE TITLE
Zen Summoning 1.3.6 No Longer Exists

### ISSUE THREAD

**Issue by RobertHDPotatoes** [TeamDman/Zen-Summoning#35]
The file ZenSummoning-1.16.5-1.3.6 is no longer available on curseforge. Not sure if you are aware of this, as now the latest version of Zen Summoning for 1.16 is ZenSummoning-1.16.4-1.3.1

**Comment by TeamDman** [comment]
It was brought to my attention that there were issues with later 1.16 builds breaking dedicated servers so I pulled them since the remaining build should still work. Existing modpack should still pull the file properly as far as I'm aware?

**Comment by RobertHDPotatoes** [comment]
Oh okay, just wanted to make sure you were aware. The only reason I noticed is because I accidentally "updated" zen summoning, down grading to the latest non-removed version and it made some of my scripts act funny
