### ISSUE TITLE
information in JEI cannot be localized

### ISSUE THREAD

**Issue by idyllist123** [TeamDman/Zen-Summoning#4]
https://imgur.com/YDVoGV3

**Comment by TeamDman** [comment]
The JEI string is grabbed from the entity's translated name
https://github.com/TeamDman/Zen-Summoning/blob/master/src/main/java/ca/teamdman/zensummoning/client/jei/AltarRecipe.java#L49
I'll look into allowing for translation of the prefix string

**Comment by TeamDman** [comment]
https://minecraft.curseforge.com/projects/zen-summoning/files/2706217
Added a localization string with parameters for quantity and entity name
Feel free to comment again if this still needs work

**Comment by xinyuan-liu** [comment]
https://github.com/TeamDman/Zen-Summoning/blob/2f36afd38924c434b5604cd050e92e48b916ccbf/src/main/java/ca/teamdman/zensummoning/client/jei/AltarRecipe.java#L32
This line also need to be localized.

**Comment by xinyuan-liu** [comment]
And the localization for entity name seems not actually working.

**Comment by TeamDman** [comment]
Thanks for the help!
New build being approved
https://minecraft.curseforge.com/projects/zen-summoning/files/2720629
Let me know if there's anything else that needs improvement!
