### ISSUE TITLE
client crash when summoning

### ISSUE THREAD

**Issue by user38898892** [TeamDman/Zen-Summoning#7]
Not sure whats happen

crash report: https://pastebin.com/ueZVbeNg
script: https://pastebin.com/NG6dZU44

**Comment by TeamDman** [comment]
Latest CurseForge build should fix this

Thanks for the report!

**Comment by user38898892** [comment]
But now the altar tells the summon succeed but actually no mobs summon.

**Comment by TeamDman** [comment]
Seems to be working for me. Are you on peaceful/is it a mob that has certain conditions to exist? More info needed
