### ISSUE TITLE
Not Consumed Catalyst

### ISSUE THREAD

**Issue by Fortist** [TeamDman/Zen-Summoning#9]
Can you add an option to not have the Catalyst consumed?
Thinking about making an item that activates all summons.

**Comment by TeamDman** [comment]
Catalyst isn't consumed, but right now it only grabs the first recipe with a matching catalyst without checking the ingredients so having 2 recipes with the same catalyst won't work. Will fix

**Comment by TeamDman** [comment]
https://www.curseforge.com/minecraft/mc-mods/zen-summoning/files/2829573
Added support for multiple summonings using the same catalyst.
The altar will pick a random summoning if multiple match the ingredients available + reagent
